name: Sirv Upload
description: 'Upload directory to Sirv'
author: 'Igor Varyvoda'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  clientId:
    description: 'Sirv client ID'
    required: true
  clientSecret:
    description: 'Sirv client secret'
    required: true
  source_dir:
    required: true
    description: 'directory to upload'
  output_dir:
    required: false
    default: /upload
    description: 'destination directory for upload'
  purge:
    required: false
    default: false
    description: 'Delete files from Sirv if no longer present in repo'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node16'
  main: 'dist/index.js'
