name: Sirv uploader
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib json
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: igorvaryvoda/gh-action-sirv@main
        with:
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          source_dir: '../upload'
        env:
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{secrets.clientSecret}}


